# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Lichun Qu
title: Lichun Qu
email: i@lichun.me
description: > # this means to ignore newlines until "baseurl:"
    Don't Be Sorry. Be Better.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lichun.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: none
