# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 屈利春 lichun.me
email: i@lichun.me
description: > # this means to ignore newlines until "baseurl:"
    Life is a playground, or nothing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lichun.me" # the base hostname & protocol for your site
twitter_username: lichun19960112
github_username:  lichun19960112

# Build settings
markdown: kramdown
